### ISSUE TITLE
require method 

### ISSUE THREAD

**Issue by xero88** [marmelab/ng-admin-demo#28]
Hello,

I'm new to this kind of javascript.

I'm wondering, from which library you get the `require` method

For example, in main.js : 
`require('./customers/config')(nga, admin);`

Thank you !

**Comment by Kmaschta** [comment]
First, welcome to the JavaScript world!

The `require` method is a native NodeJS function. It allows you to import libraries or modules.
But it's a bit more complicated than that since we use Webpack to bundle our library.

I suggest you to see some JavaScript tutorials. :)
Feel free to open an issue again if you have questions about ng-admin or this demo.
